#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [[ -z "$@" ]]; then
    echo "Usage: $0 <files>"
    exit 1
fi

for file in "$@"; do
    kind="$(yq read "$file" kind | tr '[:upper:]' '[:lower:]')"
    yq write -i -s "$SCRIPT_DIR/filters/common.yml" "$file"
    [[ -f ""$SCRIPT_DIR/filters/$kind.yml"" ]] && yq write -i -s "$SCRIPT_DIR/filters/$kind.yml" "$file"
done

