#!/bin/bash


name="$1"
output="${2:-./}"
resources="buildconfig deploymentconfig service route configmap persistentvolumeclaim imagestream deployment secret"

if [[ -z "$name" ]]; then
    echo "Usage: $0 <resource_name> [<output_dir>]"
    exit 1
fi

mkdir -p "$output"
for resource in $resources; do
    yaml=$(oc get -o yaml $resource/$name --ignore-not-found)
    [[ -z "$yaml" ]] || echo "$yaml" > "$output/$resource.yml"
done
