#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [[ -z "$@" ]]; then
    echo "Usage: $0 <files>"
    exit 1
fi

for file in "$@"; do
    kind="$(cat "$file" | yq e '.kind' - | tr '[:upper:]' '[:lower:]')"
    cat "$file" | yq e "$(cat $SCRIPT_DIR/filters/common)" - > "$file"
    [[ -f "$SCRIPT_DIR/filters/$kind" ]] && cat "$file" | yq e "$(cat $SCRIPT_DIR/filters/$kind)" - > "$file"
done
